[package]
name = "client"
version = "0.1.0"
authors = ["yml <yuemenglong@126.com>"]
build = "build.rs"

[build-dependencies.orm]
path = ".."

[dependencies]
mysql = "*"

[dependencies.orm]
path = ".."
